### ISSUE TITLE
All requests to silk's statics give 404 or 500

### ISSUE THREAD

**Issue by nabeelahmed** [django-silk/silk#102]
A sample console output (getting the following error for every request to silk's static):

```
[10/Feb/2016 11:51:00] "GET /silk/static/silk/lib/jquery.datetimepicker.css HTTP/1.1" 404 9260
[10/Feb/2016 11:51:00] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery.min.js
[10/Feb/2016 11:51:00] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery-ui-1.10.4.min.js
[10/Feb/2016 11:51:00] WARNING [django.request] Not Found: /silk/static/silk/js/cell.js
[10/Feb/2016 11:51:00] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery.datetimepicker.js
[10/Feb/2016 11:51:00] WARNING [django.request] Not Found: /silk/static/silk/js/filters.js
[10/Feb/2016 11:51:01] "GET /silk/static/silk/lib/jquery.min.js HTTP/1.1" 404 9224
[10/Feb/2016 11:51:01] "GET /silk/static/silk/lib/jquery-ui-1.10.4.min.js HTTP/1.1" 404 9254
[10/Feb/2016 11:51:01] "GET /silk/static/silk/js/cell.js HTTP/1.1" 404 9203
[10/Feb/2016 11:51:01] "GET /silk/static/silk/lib/jquery.datetimepicker.js HTTP/1.1" 404 9257
Traceback (most recent call last):
  File "C:\Python27\lib\wsgiref\handlers.py", line 86, in run
    self.finish_response()
  File "C:\Python27\lib\wsgiref\handlers.py", line 128, in finish_response
    self.write(data)
  File "C:\Python27\lib\wsgiref\handlers.py", line 217, in write
    self._write(data)
  File "C:\Python27\lib\socket.py", line 328, in write
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
```
also,

```
[10/Feb/2016 12:03:56] "GET /silk/profile/15/static/silk/css/cell.css HTTP/1.1" 404 9242
[10/Feb/2016 12:03:56] "GET /silk/profile/15/static/silk/css/summary.css HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58086)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\site-packages\django\core\servers\basehttp.py", line 150, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\SocketServer.py", line 657, in __init__
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
[10/Feb/2016 12:03:56] WARNING [django.request] Not Found: /silk/profile/15/static/silk/lib/jquery.min.js
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine
```

I just installed **django-silk==0.5.6** (django 1.5) and verified the static's path:

**C:\Python27\Lib\site-packages\silk\static\silk\lib**

or, may be I am missing on some basic local configuration.

**Comment by avelis** [comment]
@nabeelahmed Doing a quick web search shows that the client or host machine is closing the connection for some reason. This could likely be not related to this library.

For the reasons that _could_ related to this library:

- Ensure that that the file can load statically via the browser. 
- Check the settings on the browser you are using and try a different browser.
- Try running your Django server under a different configuration.
- Verify file permissions on your site packages path.

I realize you are running this on a windows machine and I found the following [StackOverflow issue](http://stackoverflow.com/questions/17854713/error-errno-10053).

Lastly, Django 1.5 is no longer supported in this library from at least version (0.5.6). You can find an earlier version and possibly see how that works but I can't make any guarantees.

I hope this information helps.

**Comment by nabeelahmed** [comment]
@avelis I appreciate your prompt response.
I have edited the issue title and comment, to make it more clear.
Yh, that 'connection aborted by the host' must be something wrong at my end, probably the very slow django dev server.

> Lastly, Django 1.5 is no longer supported in this library from at least version (0.5.6). You can find an earlier version and possibly see how that works but I can't make any guarantees.

Thanks for pointing it out, I'll to try downgrade silk and see if the 404s 'll go.

**Comment by avelis** [comment]
@nabeelahmed Using Django==1.5.12 and the example app in this repo I didn't run into any 404's.

It would appear that there is the word path name `/silk/`being prefixed to all of your static file references.

If you are testing out locally using the `runserver` command you shouldn't need to run collectstatic. That is mostly used in a production setting.

If you are still running into the prefix url path issue, checkout your settings and see what your `STATIC_ROOT` is set to as well as your `STATIC_FILES_DIRS`.

I hope my further advice can help you some more.

**Comment by nabeelahmed** [comment]
@avelis 

`STATIC_ROOT = os.path.join(PROJECT_DIR,'static/')`
`STATICFILES_DIRS = ()`
```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    #    'django.contrib.staticfiles.finders.DefaultStorageFinder',
```

The project is in production for last 4 years - 50+ apps - so hopefully the static conf, etc must be ok.

The statics didn't work locally, so I ran `collectstatic `it solved the issue somewhat i.e. get 200 for few and 404 and 500 for other statics:

```
[24/Feb/2016 12:00:15] "GET /static/silk/js/filters.js HTTP/1.1" 200 1308
[24/Feb/2016 12:00:15] "GET /static/silk/filter2.png HTTP/1.1" 200 3006
[24/Feb/2016 12:00:15] "GET /static/silk/js/cell.js HTTP/1.1"** 500** 92456
[24/Feb/2016 12:00:15] "GET /static/silk/lib/jquery-ui-1.10.4.min.js HTTP/1.1" 200 228539
[24/Feb/2016 12:00:15] "GET /static/silk/lib/jquery.datetimepicker.js HTTP/1.1" **500** 92690
[24/Feb/2016 12:00:15] "GET /static/silk/lib/jquery.min.js HTTP/1.1" 500 92547
[24/Feb/2016 12:00:19] "GET /static/silk/fonts/fira/FiraSans-Light.woff HTTP/1.1" 200 95406
[24/Feb/2016 12:00:19] "GET /static/silk/fonts/fira/FiraSans-Medium.woff HTTP/1.1" 200 89883
[24/Feb/2016 12:01:02] "GET /silk/profiling/ HTTP/1.1" 200 31104
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/css/fonts.css
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/css/colors.css
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery-ui-1.10.4.min.css
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/css/cell.css
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/css/numeric.css
[24/Feb/2016 12:01:03] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery.datetimepicker.css
[24/Feb/2016 12:01:05] "GET /silk/static/silk/lib/jquery-ui-1.10.4.min.css HTTP/1.1" **404** 9257
[24/Feb/2016 12:01:05] "GET /silk/static/silk/css/fonts.css HTTP/1.1" **404** 9212
[24/Feb/2016 12:01:05] "GET /silk/static/silk/css/colors.css HTTP/1.1" **404** 9215
[24/Feb/2016 12:01:05] "GET /silk/static/silk/css/numeric.css HTTP/1.1" **404** 9218
[24/Feb/2016 12:01:05] "GET /silk/static/silk/css/cell.css HTTP/1.1" 404 9209
[24/Feb/2016 12:01:05] "GET /silk/static/silk/lib/jquery.datetimepicker.css HTTP/1.1" 404 9260
[24/Feb/2016 12:01:05] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery.min.js
[24/Feb/2016 12:01:05] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery-ui-1.10.4.min.js
[24/Feb/2016 12:01:05] WARNING [django.request] Not Found: /silk/static/silk/js/cell.js
[24/Feb/2016 12:01:05] WARNING [django.request] Not Found: /silk/static/silk/lib/jquery.datetimepicker.js
[24/Feb/2016 12:01:05] WARNING [django.request] Not Found: /silk/static/silk/js/filters.js
[24/Feb/2016 12:01:06] "GET /silk/static/silk/lib/jquery.min.js HTTP/1.1" 404 9224
[24/Feb/2016 12:01:06] "GET /silk/static/silk/lib/jquery-ui-1.10.4.min.js HTTP/1.1" 404 9254
[24/Feb/2016 12:01:06] "GET /silk/static/silk/js/cell.js HTTP/1.1" 404 9203
[24/Feb/2016 12:01:06] "GET /silk/static/silk/lib/jquery.datetimepicker.js HTTP/1.1" 404 9257
[24/Feb/2016 12:01:06] "GET /silk/static/silk/js/filters.js HTTP/1.1" 404 9212
[24/Feb/2016 12:01:06] WARNING [django.request] Not Found: /silk/static/silk/filter.png
[24/Feb/2016 12:01:06] "GET /silk/static/silk/filter.png HTTP/1.1" 404 9203
```

**Comment by kqdtran** [comment]
Hi, I seem to be running into the same issue too. Some static files were present, but some were missing. I've run `collectstatic` and followed every other steps described in this discussion. Is there something else that I should be doing to get all the static files to show up correctly.

![screenshot from 2016-12-02 15-11-38](https://cloud.githubusercontent.com/assets/2239263/20848796/ab576848-b8a1-11e6-9657-015f9719f874.png)
