### ISSUE TITLE
[Error][Bug]adding silk middleware in MIDDLEWARE causes ImportError

### ISSUE THREAD

**Issue by shahakshay94** [django-silk/silk#108]
I followed the docs and tried to add the middleware line in different positions in MIDDLEWARE settings file, but I am getting "ImportError: No Module named context_processors"
Below is my full stack-trace of my error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 44, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/silk/middleware.py", line 32, in <module>
    fpath = silky_reverse('summary')
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/silk/middleware.py", line 23, in silky_reverse
    r = reverse('silk:%s' % name, *args, **kwargs)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 522, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 269, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 372, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/akki/rest_api/rest_apis/urls.py", line 19, in <module>
    urlpatterns += patterns('', url(r'^silk/', include('silk.urls', namespace='silk')))
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/silk/urls.py", line 7, in <module>
    from silk.views.requests import RequestsView
  File "/home/akki/rest_api/venv/local/lib/python2.7/site-packages/silk/views/requests.py", line 1, in <module>
    from django.template.context_processors import csrf
ImportError: No module named context_processors
[03/May/2016 06:48:16] "GET /silk/ HTTP/1.1" 500 59

```

Below is my MIDDLEWARE settings:

```
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'silk.middleware.SilkyMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)
```

**Comment by alexkunger** [comment]
I'm getting the same issue

**Comment by avelis** [comment]
@shahakshay94 
Do you know what version of Django you are running and what version of Silk you are trying to use?

**Comment by avelis** [comment]
This is likely caused by this change that trying to determine where to import csrf based on what version of Django.
https://github.com/django-silk/silk/commit/c1ed0eb2e735d72d1c3e9ef3e1a620f89b8dd5dd

**Comment by alexkunger** [comment]
I'm on Django 1.7.8 and Silk 0.5.7

**Comment by alexkunger** [comment]
I have found the issue.

The 0.5.7 release available at https://pypi.python.org/pypi/django-silk does not contain the code here: https://github.com/django-silk/silk/compare/0.5.7...master which is what github says is in 0.5.7

**Comment by shahakshay94** [comment]
I have Django v1.7.1 and Silk v0.5.7

**Comment by avelis** [comment]
@shahakshay94 Release v0.6.0 should be available with the changes you are looking for. https://github.com/django-silk/silk/releases/tag/0.6.0
