### ISSUE TITLE
Local Dev of Silk. Template Error.

### ISSUE THREAD

**Issue by hanleyhansen** [django-silk/silk#121]
Trying to do some dev on silk but the local project isn't working? I installed migrations and made migrations for the `example_app` project but when i run it and visit the `example_app/` route i got the following error. Bad templates config? The settings file looks like it's for an older version of Django yet the requirements list a django dependency of >1.8 which is when the new `TEMPLATES` settings structure was introduced.

```bash
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
    response = self.get_response(request)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/hanleyhansen/git/silk/project/example_app/views.py", line 16, in index
    return render('example_app/index.html', {'blinds': models.Blind.objects.all()})
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/hanleyhansen/venv/silk/lib/python2.7/site-packages/django/template/loader.py", line 43, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: {'blinds': []}
[08/Jul/2016 13:19:31] "GET /example_app/ HTTP/1.1" 500 59
```

Any ideas? Or am I doing this wrong? Can you add some docs around local dev. Would love to contribute to this project as we are introducing it to our infrastructure.

**Comment by hanleyhansen** [comment]
Start this PR to try to get things going. https://github.com/django-silk/silk/pull/122

Any feedback appreciated.

**Comment by hanleyhansen** [comment]
This issue was resolved in my linked pr. Will close once my pr is merged.

**Comment by avelis** [comment]
@hanleyhansen I merged your PR. Thanks for addressing this issue. I greatly appreciate you fixing the failing unit tests.
