### ISSUE TITLE
Latest version of django-silk not installing because of missing dependency

### ISSUE THREAD

**Issue by hanleyhansen** [django-silk/silk#127]
A fresh install of the latest version from pypi results in the following.

```bash
(test-silk) default hanleyhansen@Hanley-Hansen-MBPM ~ [10:59:37]
$ pip install django-silk
Collecting django-silk
  Downloading django-silk-0.6.0.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 412kB/s
    Complete output from command python setup.py egg_info:
    warning: pypandoc module not found, could not convert Markdown to RST
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/k4/vxmtlnfn34jc3k4yfvv52sdc0000gp/T/pip-build-di0Wg2/django-silk/setup.py", line 13, in <module>
        README = read_md('README.md')
      File "/private/var/folders/k4/vxmtlnfn34jc3k4yfvv52sdc0000gp/T/pip-build-di0Wg2/django-silk/setup.py", line 11, in read_md
        def read_md(f): return open(f, 'r').read()
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/k4/vxmtlnfn34jc3k4yfvv52sdc0000gp/T/pip-build-di0Wg2/django-silk
You are using pip version 8.0.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(test-silk) default hanleyhansen@Hanley-Hansen-MBPM ~ [10:59:44]
$
```

Should `pypandoc` be added to `setup.py` as a dependency? Or should we remove it the dependency on it? `pandoc` seems like overkill for just converting this readme file.

cc: @avelis

**Comment by avelis** [comment]
@hanleyhansen It's an honest question. I did it to convert the markdown file to rst when publishing releases to pypi. This was a mistake on my end to assume that the markdown readme was included in the package.

**Comment by hanleyhansen** [comment]
So go with just the markdown should suffice? I can put together a PR. I think users in general would prefer that to adding a big package like pypandoc.

**Comment by hanleyhansen** [comment]
We have a PR incoming that'll simplify this a tad and should get it working again.
